Push CSM Project Details widget to repository.
platform-experience/serviceportal-widget-library pull request #134
Opened 2019-06-25 22:17 UTC by madison-spina

2019-07-09 14:39 UTC, asc2683 requested changes
Comments with "check box" require changes. Please confirm the changes by checking the check box when you're done.

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/config.json
> +  "solution-details": "",
- [ ] Fill out and complete solution details

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-body-html-template.html
> +          <p class="cell-content">{{::data.proj.status}}</p>
Good use of one-way binding 👍

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-client-script.js
> +			'background-color' : '#71E279'
Consider using ng-style

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-client-script.js
> +		if (!name)
Good use of intention revealing function name 👍

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-css.scss
> +    vertical-align: middle !important;
Use !important sparingly. Instead try with CSS specificity.
https://specificity.keegan.st/
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-css.scss
> +  #foot-text {
Consider adding a class instead of styling the ID.

`<div id="footer" class="some-footer-class" ></div>`

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-css.scss
> +  }
Consider using REM for fonts, margin and paddings instead of PX

2019-07-09 14:39 UTC, asc2683 commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-server-script.js
> +
Awesome job in naming your functions! 💯 
https://www.freecodecamp.org/news/how-to-make-your-code-better-with-intention-revealing-function-names-6c8b5271693e/

2019-10-03 16:36 UTC, stevengregory requested changes

2019-10-03 16:36 UTC, stevengregory commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-client-script.js
> +  /* widget controller */
With a named controller function in place; which is self descriptive of purpose, you can feel free to remove the /* widget controller */ comment.

2019-10-03 16:36 UTC, stevengregory commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-body-html-template.html
> +                          uib-tooltip="{{::data.proj.prj_mngr}}"
Props for use of one-way binding. 👍

2019-10-03 16:36 UTC, stevengregory commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-option-schema.json
> +[{"name":"title","section":"other","default_value":"Project details","label":"Title","type":"string"}]
If you could please format this JSON so that  it renders well on the library portal and reads well. Thanks!

2019-10-03 16:36 UTC, stevengregory commented on src/pe-csm-project-details/widget/pe-csm-project-details.u-server-script.js
> +})();
Looks good. 👍

2019-12-10 01:16 UTC, closed without merging