Feature/pe employee recognition nominate
platform-experience/serviceportal-widget-library pull request #140
Opened 2019-06-27 18:34 UTC by jforjacob

adding 2 widgets - part of an application but I think still library-worthy items. I'll add fuller documentation soon.

2019-07-09 19:22 UTC, asc2683 requested changes
Comments with check box needs fixing. Please mark with check after done.

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/config.json
>  }
👍

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-client-script.js
> +
consider using controller as syntax and named controllers

https://github.com/platform-experience/serviceportal-best-practice#named-controllers

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-client-script.js
> +	}
- [ ] add call back fn in case of error and notify the user with error message.

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-css.scss
> +  padding-top: 1rem;
good use of REM 👍

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-server-script.js
> +		cGR.addQuery('opened_by', gs.getUserID());
consider making the variable name more meaningful. 

https://medium.com/coding-skills/clean-code-101-meaningful-names-and-functions-bf450456d90c

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-server-script.js
> +			if ( myCandidateIds.indexOf(uGR.getUniqueValue()) === -1 ) {
👍 triple equals

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-vote/config.json
> +  "solution-details": "A widget to vote for employee recognition, part of a voting application.",
👍

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-vote/widget/pe-employee-recognition-nominate.u-client-script.js
> +	}
- [ ] add if error call back function and notify user of error msg

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-vote/widget/pe-employee-recognition-nominate.u-css.scss
> +  margin-left: 6rem;
- [ ] update px with rem for margins - be consistent

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-vote/widget/pe-employee-recognition-nominate.u-server-script.js
> +		return;
consider 2 or 4 spaces instead of 8

2019-07-09 19:22 UTC, asc2683 commented on src/pe-employee-recognition-nominate/widget/pe-employee-recognition-nominate.u-server-script.js
> +				name: cGR.name.toString(),
question: is the use of .toString() necessary? .getDisplayValue()?

2019-10-04 15:26 UTC, stevengregory commented
@jforjacob did you get a chance to checkout the change requests -- anything I can do to help?

2019-12-10 16:29 UTC, closed without merging